apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogdep
  labels:
    type: app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: blog
          image: 6esusigugh/susigughimg:0109

